name: sky_cast
description: "Sky Cast - Weather"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  go_router: ^17.0.0
  dio: ^5.9.0
  envied: ^1.3.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  envied_generator: ^1.1.1
  riverpod_generator: ^2.6.5
  json_serializable: ^6.8.0

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  
